// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm0dKHWHnn08VpuL9z7Z68b4Cmpk4ladg',
    appId: '1:449982502816:web:1e54818acf8af7f2d336c5',
    messagingSenderId: '449982502816',
    projectId: 'chaternamel',
    authDomain: 'chaternamel.firebaseapp.com',
    storageBucket: 'chaternamel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXJ8KZB0otWjonP0JBEHWVskOt323pc4I',
    appId: '1:449982502816:android:709d5cb5d814227fd336c5',
    messagingSenderId: '449982502816',
    projectId: 'chaternamel',
    storageBucket: 'chaternamel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlLu_YhH0185GI1uuOY6tMs9sREHRly9o',
    appId: '1:449982502816:ios:599d92303f59dd17d336c5',
    messagingSenderId: '449982502816',
    projectId: 'chaternamel',
    storageBucket: 'chaternamel.firebasestorage.app',
    iosBundleId: 'com.example.tecChatCelaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlLu_YhH0185GI1uuOY6tMs9sREHRly9o',
    appId: '1:449982502816:ios:599d92303f59dd17d336c5',
    messagingSenderId: '449982502816',
    projectId: 'chaternamel',
    storageBucket: 'chaternamel.firebasestorage.app',
    iosBundleId: 'com.example.tecChatCelaya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm0dKHWHnn08VpuL9z7Z68b4Cmpk4ladg',
    appId: '1:449982502816:web:105613cdba1f25fbd336c5',
    messagingSenderId: '449982502816',
    projectId: 'chaternamel',
    authDomain: 'chaternamel.firebaseapp.com',
    storageBucket: 'chaternamel.firebasestorage.app',
  );
}
